version: '3.1'

services:

  auth_db:
      image: mariadb:latest
      container_name: auth_db
      ports:
        - 3333:3306
      environment:
        MYSQL_ROOT_PASSWORD: 'test'
        MYSQL_DATABASE: 'auth'
        MYSQL_USER: 'test'
        MYSQL_PASSWORD: 'test'
      volumes:
        - auth:/var/lib/mysql
        - ./init_auth.sql:/docker-entrypoint-initdb.d/init_auth.sql:ro

  data_db:
    image: mariadb:latest
    container_name: data_db
    ports:
      - 4444:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
    volumes:
      - ./init_data_games.sql:/docker-entrypoint-initdb.d/init_data_games.sql
      - ./init_data_expansions.sql:/docker-entrypoint-initdb.d/init_data_expansions.sql
      - ./init_data_households.sql:/docker-entrypoint-initdb.d/init_data_households.sql
      - data:/var/lib/mysql

volumes:
  auth:
  data:
