version: '3.1'

services:

  mysql1:
      image: mariadb:latest
      ports:
        - 3333:3306
      environment:
        MYSQL_ROOT_PASSWORD: 'test'
        MYSQL_DATABASE: 'test'
        MYSQL_USER: 'test'
        MYSQL_PASSWORD: 'test'

  mysql2:
    image: mariadb:latest
    ports:
      - 4444:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
