version: '3.1'

services:

  auth_db:
      image: mariadb:latest
      container_name: auth_db
      ports:
        - ${AUTH_PORT}:3306
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: 'auth'
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
        - ./init_auth.sql:/docker-entrypoint-initdb.d/init_auth.sql:ro

  data_db:
    image: mariadb:latest
    container_name: data_db
    ports:
      - ${DATA_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./init_data_games.sql:/docker-entrypoint-initdb.d/init_data_games.sql
      - ./init_data_expansions.sql:/docker-entrypoint-initdb.d/init_data_expansions.sql
      - ./init_data_households.sql:/docker-entrypoint-initdb.d/init_data_households.sql

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile_bot
    depends_on:
      - auth_db
      - data_db
    volumes:
      - ../src:/src
    tty: true
    command: python3 /src/main.py





